### ISSUE TITLE
New Qt Wallet user doc needs to be added to wiki

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/docs#16]
A new user document for the Notification Windows feature has been added at: https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/notifications.md

Please add a link to this document in the wiki sidebar once we release Qt wallet (supposed to be next week).
For now I think it can go after "Lock outputs to prevent spending". I think you can just name it "Notification Windows" as everything under Managing Funds relates to MWC Qt Wallet.

**Comment by MrCryptoT** [comment]
Will be included accordingly, thanks for the Headsup! ☕ 

Thinking of the "Managing Funds" Section, I would suggest to rename it to something more broad like "Management & Preferences", then Ill just include it in there if your not oposed to that.

**Comment by scasaletto** [comment]
What would you think of something like "Managing Funds with GUI Wallet" to help point new users to this section. Our Starter Guides section has no information about the GUI Wallet and we need some way to catch the attention of new users. Eventually we'll need to write a User's Guide for MWC Qt Wallet and all of the docs we have now give more detailed information about different features of the wallet and how to use them.

**Comment by MrCryptoT** [comment]
A Notification Feature is not really connected to "managing funds", hence I'd try to get rid of the "funds" in that title to be a bit more general.
How about "GUI Wallet Management" to elaborate on QT Handling&Settings in general?

In the "Starter Guides"-Section there's truly not a single QT Guide yet, Hence I added a remark above that ;
`If you are using the QT Wallet the detailed Guides are all you should need to get started.`
This may not be sufficient in catching user's attention I admit. 
Maybe a simple link to the relevant QT section in "Starter Guides" would be enough ?
![image](https://user-images.githubusercontent.com/8693733/97094149-7b7f4600-1652-11eb-95aa-771831e3006f.png)

**Comment by MrCryptoT** [comment]
Got included accordingly, Ill try to revisit visibillity once again at a later point to make sure poeple find the ressources they need for the QT wallet. Thanks alot! ☕ 🥳  Also feel free to leave further feedback =)
