### ISSUE TITLE
Link to Offline Secure Storage on https://www.mwc.mw/resources return 404

### ISSUE THREAD

**Issue by dennisvanderpool** [mwcproject/docs#17]
Steps to reproduce:
1) Goto https://www.mwc.mw/resources
2) Click on Offline Secure Storage
3) 404 => Currently points to https://github.com/cgilliard/mwc/blob/master/doc/offline_wallet.md

Is there another repo for the website?

**Comment by MrCryptoT** [comment]
I think thats the page you are looking for @dennisvanderpool : 
https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/cold_wallet.md

Fixed the incorrect link, thanks for letting us know!
